name: Schedule update

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "5 0 * * *"

jobs:
  build:
    name: Schedule update stats
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MARKDOWN_FILE: README.md
      GIST_ID: f5eada56197da823b4cac1050a267745

    strategy:
      matrix:
        node_version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Clone and run productive-box
        run: |-
          git clone https://github.com/sunchaser-lilu/productive-box.git
          node productive-box/dist/index.js
      - name: Commit and push
        run: |-
          git config --global user.email "admin@lilu.org.cn" && git config --global user.name "sunchaser-lilu"
          git diff
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull --rebase && git push
