name: Schedule update

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "5 0 * * *"

jobs:
  build:
    name: Schedule update stats
    runs-on: ubuntu-latest
    env:
      TIMEZONE: Asia/Shanghai
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MARKDOWN_FILE: README.md
      PRODUCTIVE_GIST_ID: f5eada56197da823b4cac1050a267745
      NETEASE_GIST_ID: 475826c54f1a5cd2037aa96c604043c0
      NETEASE_USER_ID: 270914295
      NETEASE_USER_TOKEN: ${{ secrets.NETEASE_USER_TOKEN }}
      DOG_GIST_ID: e85d2e5765110be1d8cfe57f2557a130
      DOG_WIDTH: 63
      DOG_FILL_LEN: 103

    strategy:
      matrix:
        node_version: [14]
    steps:
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Clone and run productive-box
        run: |-
          git clone https://github.com/sunchaser-lilu/productive-box.git
          node productive-box/dist/index.js
          git clone https://github.com/sunchaser-lilu/netease-music-box.git
          cd netease-music-box
          yarn install
          cd ..
          node netease-music-box/index.js
          git clone https://github.com/sunchaser-lilu/sunchaser-dog-box.git
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run dog-box
        run: |-
          cd sunchaser-dog-box
          mvn -B package --file pom.xml
          java -jar target/dog-box-1.0-SNAPSHOT.jar
      - name: Commit and push
        run: |-
          git config --global user.email "admin@lilu.org.cn" && git config --global user.name "sunchaser-lilu"
          git diff
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull --rebase && git push
